---
title: "Introduction"
author: "Bruce Cochrane"
date: "2022-07-20"
output: html_document
---
# Introduction 

Cooking has always been a big part of my life, but since I retired from my career as a geneticist, I have had more time to explore new areas.  In particular, two factors have become central to my culinary efforts:

## Bread

I have long been fascinated by sourdough cooking - I successfully made my first starter (on the first try!) in 1974 and managed to keep it going for a few years before moves and inattention doomed it to oblivion.  When I moved to Ohio in 2007, my interest was rekindled, especially after I discovered Reinhardt's *Artisanal Bread at Home*.  His starter recipe took a couple of trys, but the use of "organic" flour and pineapple juice in the initial mix proved successful.  That starter is now about 13 years old and going strong (I'll talk about maintenance in Chapter 2).  

The second piece in by bread baking evolution was a result of my wife's Christmas gift of *Tartines* in 2021.  This is a fascinating book, one which interweaves recipes with detailed explanations of the reason for each step and photographs of how the steps are performed.  The recipes are fairly involved, and following them from the book involves a lot of page turning (NOT something I'd want to do with an ebook), but the results can be spectacular.  Again, in Chapter 2, I will provide some simplified ideas to facilitate your efforts.

## The Big Green Egg

In 2011, Alice and I embarked on a major project to finish the basement of her (now our) home.  So what does this have to do with cooking?  Nothing directly, however while shopping for a gas fireplace, we saw our first [Big Green Egg](http://www.biggreeneg.com) and decided we wanted one (she mostly for its appearance, me for the intriguing cooking possibilities).  Shortly thereafter, we purchased a medium one, and while we had a lot of fun with it (initially for pizza and baked potatoes), it soon became apparent that we needed a larger one.  Accordingly, a few years later, I sprung for a large one.  I will have more to say about it in the [Big Green Egg](#bge) section.

Over the subsequent years, my Green Egg recipe portfolio has diversified.  Most of what I do can be divided into two categories - grilling and barbecuing.  Grilling is what most casual outdoor cooking enthusiasts are most familiar with - cooking over high heat, often with some sort of basting sauce, with cooking times usually measured in minutes.  Barbecuing, by contrast, involves "low and slow" cooking (temperatures maintained at 150-250^o^ F.) and cook times measured in hours.  The results, with properly monitored cooking, can be outstanding.


## Other Stuff

But you might say things like "man doesn't live by bread alone" or "what about the winter months?".  Both are valid critiques, so in subsequent sections, I will describe some indoor cooking recipes I've come to depend on.  And I'll be quite honest - I really don't go for admittedly healthy options like, perhaps, green bean and kale salad.  So I've entitled the chapter [Comfort Food](#comfort), reflecting the fact that, while the recipes are perhaps not the stuff of a dietitian's dream, they are (at least to me) fun to eat.  Furthermore, most of them don't require a whole lot of cooking time. Some of them are modifications of ones originally found in cookbooks (which are cited), but which I have modified for either flavor or ease of cooking reasons.  A good example of this is the recipe for macaroni and cheese - the sauce is originally from the venerable *Joy of Cooking* but modified to increase the spiciness and make use of a microwave oven.

## A Note on Portion Size and Original Sources

Everyone is familiar with estimated serving numbers in published recipes.  In general, I find them to be rather inaccurate, so when trying a new recipe,  I use them at most for a rough guideline.  And personally, what I found to be a single serving for me 50 years ago is  a serving plus leftovers or even two servings for me today.  All of the recipes I've included are of that size; you of course may find otherwise.

And finally, I will confess that there are almost no purely original recipes in this book - all are ones that were originally obtained from an online source. Those sources are cited in the recipes themselves, and all sources, with brief annotations, are provided in the concluding chapter. 



