# Kitchen Essentials {#essentials}

So the bad news is that there is an enormous number of kitchen gadgets, utensils, dishes, bowls and table top appliances out there eager to drain your wallet.  The good news?  You don't need most of them.  Beyond the items found in every kitchen (stove, refrigerator, mixing bowls, etc.) there are only a few items that will make your life easier, and in fact you can cook perfectly adequately without them.  Here are a few that I use on a regular basis.

## Bread Making

The following can be done without, but I consider them to be all but essential.

1.  **A stand mixer**.  The two cookbooks I recommend in the [Bread](#bread) section have different takes on this.  Reinhardt calls for using one in almost every recipe, while I'm pretty sure that Robertson (*Tartines*) doesn't even mention them.  I happen to use one wherever possible, even when the recipe doesn't call for it (and will do do so throughout the recipes).  Ours is a Viking that, as far as I can tell, is no longer being manufactured (although you may find a used one available on ebay or some similar site).  The much more common ones, of course, are those of [Kitchenaid](https://www.kitchenaid.com/countertop-appliances/stand-mixers.html), definitely fine machines. They come in two sizes , 4 qt. and 5.5 qt.  I received one of the former as a wedding present 40 years ago, and it served all of my needs at the time just fine (indeed, it is now at my lakefront cottage in the Finger Lakes and still going strong.  Were I to buy one today (or if our Viking dies), I would probably go with the larger one.
2.  **A kitchen scale**.  Most breadmakers will recommend that weight be used to measure ingredients.  This is particularly important for flour, since even different bags of the same brand can have different densities.  You can get a decent electronic one for around $25. 

## Grilling

## Indoor Cooking

In general, all you need here is a decent selection of pots, pans and bowls.  However, I do recommend considering the following:

1. An **immersion blender**.  I never really thought about one of these until I heard an NPR piece on possible Christmas gifts for the cooks in one's life.  I immediately thought of my younger son John, so I got him one and he liked it.  I subsequently purchased one for myself, a Braun, that is not only a blender but can also be a small blender and chopper, useful for things like grating hard cheese and chopping garlic.
2.  A **slow cooker**.  This is definitely a secondary priority, since most recipes that call for one can easily be adapted for the stove top or oven.  However, it is nice to be able to throw a meal together and forget about it for a few hours.  I've included some recipes that use it, but I've also made suggestions as to how to cook them conventionally.
3.  A **convection toaster oven**  In the summer months, it's nice to be able to cook in one of these and avoid heating up the house by using the oven.  
4.  Only a few of these recipes call for using a **microwave oven**, but one is great to have, especially for thawing and warming leftovers.  
5.  Finally, you may ask, what about an **Instant Pot** or the equivalent.  A couple of comments:  First, these are at their core programmable pressure cookers.  I've used stove top pressure cookers on and off for years, so I understand their allure.  However, while I do have one in my lake house in New York, I've never gotten around to buying one for our Ohio home.  I've included one recipe (for [fajitas](#fajitas) that I particularly like, but it can also be prepared on the grill.  So if you want to, go for it - the internet has almost as many IP recipes as it does cat videos, so there will be a lot for you to explore.
