# Drinks  

One of the things I always liked about *The Joy of Cooking* (at least the edition I own) is that includes a section of alcoholic beverage recipes.  Understand, I am not a big consumer of cocktails, but there are a few specialty drinks that I rather like (aside from basics like gin and tonic, scotch and soda, etc).  So I'm including a few here, and may add more as I discover more.

## A note on spirits

There was a time when I got by on inexpensive brands of scotch, bourbon and gin.  However, that was a time when a) hard liquor was a bigger part of my life, and b) I didn't have much money.  However, as I got older and wiser (I think) I found that I could still enjoy life by drinking less and moving up in quality (the same goes for wine and beer, but that's another story).  So here are a few brief comments and suggestions.

### Bourbon and Rye

I spent years using bourbon as the go-to domestic whiskey (even sinking to the low of shots and beers), but like many others, a few years ago I discovered rye, a whole new world of flavor.  The word "spicy"  is often applied to it, and it fits.  My current favorite is Elijah Craig, but there is also a world of "craft" bottles to explore.  A good place to do so is [Seelbach's](https://seelbachs.com/), an online marketer of craft spirits of all sorts.

### Gin

Flavors of gin are determined by the particular herbal recipe used in its production, so finding the right one is definitely a matter of personal taste.  For me, Tanqueray (in the green bottle) is an excellent mass market product.  I haven't explored craft gins all that much, but when I'm in the Finger Lakes, especially in summer, I pick up a bottle or two of Finger Lakes Distilling's [Seneca Drum](https://fingerlakesdistilling.com/our-products/gin/).  Again, due to our arcane liquor laws, you will likely need to travel to the Finger Lakes to find it.  If you can't do that, Seelbach's has lots of choices, and if you live in a more enlightened state, there may be local choices to explore.

### Tequila

I am not really an expert in these; suffice it to say that, while margarita recipes call for silver, we go for gold, typical a単ejo.  When we were in Mexico a few years ago, we stopped at a store that sold literally hundreds of bottles, but the selection was so overwhelming that we ended up leaving empty handed.

## Recipes

### King's Spicy Margarita

A couple of years ago, we discovered jalape単o-spiced margaritas while on a holiday trip to Charleston.  I had my doubts, but in fact it was quite good.  [This recipe](https://www.winemag.com/recipe/kings-spicy-margarita/), from *Wine Enthusiast*, looks like a good one.

**Ingredients**

> 2 ounces your favorite tequila    
> 3 tablespoons freshly squeezed lime juice  
> 1.5 tsp. light agave nectar  
3-5 dashes [Green Chili Bitters](https://www.kingfloyds.com/collections/culinary-bitters/products/king-floyds-green-chili-bitters); also available on [Amazon](https://www.amazon.com/King-Floyds-Green-Bitters-Cocktails/dp/B09B4B84P5)   
Salt, lime wedge, and jalape単o slices for garnish  

1.  combine all of the ingredients except the garnish, in a cocktail shaker.
2.  Shake for 30 seconds and strain into a ice filled salt rimmed glass.
3.  Garnish with lime and jalape単o slices (to taste).



### "Perfect" Manhattan

This is one from *The Joy of Cooking*, and it has been a staple throughout my life.  When I was younger, I was intimidated by the price of angustura bitters, however I now realize that a dash takes this drink from a tasty alcohol source to an actual cocktail.  Also, while I used bourbon for years, more recently I've come to favor rye whiskey.  And this recipe makes a single drink, but it can easily be scaled up for company (my parents used to treat themselves to a pitcher of Manhattans every Sunday afternoon).

**Ingredients**

2 oz bourbon or rye  
1/3 oz dry vermouth  
1/3 oz sweet vermouth  
dash of Angostura bitters  
Maraschino cherry (optional)  

1. Pour the bourbon and vermouths over ice in an old fashioned glass.   
2.  Add the bitters and stir briefly.  Garnish with the cherry if desired.
