
# Explorations

As I get older, I find myself getting more adventuresome in the kitchen.  Thus, I am constantly trying new things out, some of which succeed and others which don't.  In this section, I'm going to include new recipes as I find them, and then add notes and possible modifications based on the results.

## More Breads

### Honey Wheat Sourdough Sandwich Bread {#HoneyWheat}

Thus far, the only bread recipe involving use of conventional loaf pans is [Parmesan Bubble Loaf](#PBL), and of course it is hardly a conventional bread.  My wife's Christmas gift of a Tupperware Micropro Grill (more below) gave me the opportunity to make excellent grilled sandwiches, so I obviously needed a sandwich bread for them.  This one is from [Little Spoon Farms] and seemed like a good place to start.  I've incorporated what is now the standard procedure for dough preparation and proofing.

**Ingredients**

For the starter:

>  15 gm sourdough starter (1 tbsp)  
50 gm all purpose or bread flour  
50 gm water

For the dough:

> 100 gm starter (all of it)  
325 gm water  
2 tbsp honey (don't try to weigh this)  
10 gm salt  
125 gm whole wheat flour  
375 gm bread flour

1.  The night before preparing, mix all the starter ingredients in a small bowl.  Cover and place in a warm location.
2.  Add all of the ingredients to a large bowl.  Stir first with a spatula and then with your hands to hydrate all of the flour (a stand mixer would work as well - about 30 seconds on the lowest setting with a paddle attachment).  Let the dough stand for one our.
3.  Wet your hands and perform a stretch and fold.  Repeat the process every 30 minutes for 3-4 hours, until the dough has become fluffy.
4.  Place the dough onto a lightly floured surface.  Shape it into a rectangle and fold inward from both sides, and similarly from top and bottom.  Place it into a lightly oiled 9" X 5" loaf pan.
5.  Allow the loaf to rise in a warm place for another 3-4 hours.
6.  Preheat your oven (or toaster oven) to 375^o^ F.  
7.  Bake the bread for 45 minutes.
8.  Allow the bread to cool in the pan for 10-15 minutes before placing on a cooling rack.

#### Comments

1.  Initial bake yielded an excellent loaf of bread.  I tried it for a cheese sandwich (see below), and it toasted well.  However, it is a strongly flavored bread, so use of similarly flavored cheese is recommended.  Store bought "cheddar" was uninspiring; swiss cheese was somewhat better.

#### Possible Modifications

This might be better with less whole wheat flour and more bread flour.  Of course that also means adjusting the amount of water as well.  Based on another Little Spoon Farms recipe (for, of all things, sourdough bread baked in a slow cooker), We could try the following mix:

> 100 gm starter  
350 gm water  
50 gm whole wheat flour  
450 gm bread flour  
2 tbsp honey  
10 gm sea salt  

#### Results

Both formulations yielded bread with excellent texture and flavor.  The original recipe, of course, has more of a whole wheat flavor, and the tang of sourdough is somewhat muted.  The second recipe yields more of a traditional white bread, and the sourdough notes are more prominent.  I somewhat prefer it, but that  is just a matter of taste.  Try them both and decide for yourself.

### Crumpets

When was a child, my mother would make a simple delicacy which she called "crumpets" - split English muffins, topped with a slice of American cheese and two small pieces of bacon, and broiled until the cheese melted and the bacon curled.  I haven't prepared them in decades and don't intend to now.  However, I recently ran across [this recipe](https://www.splendidtable.org/story/2023/01/21/crumpets){target="_blank"} for the real thing on the Splendid Table web site.  I'm going to give it a try - first as described and then using sourdough.  First the original recipe:

**Ingredients**

> 100 gm bread flour  
> 65 gm warm water  
70 gm whole milk  
1/2 tsp dry yeast  
1/2 tsp sugar  
1/2 tsp fine sea salt  
3/4 tsp baking powder  
1 tsp cold water  
vegetable oil for greasing.

1.  Combine all except the last three ingredients and whisk together to make a smooth batter.  Let batter stand in a warm place until very bubbly, about 1 hour.
2.  When the batter is ready, combine the baking powder with the water and mix into the batter.
3. Lightly grease a frying pan and some 4 inch crumpet rings (if you don't have these, you can cook these like pancakes, making what the British call "pikelets").
4.  Place the rings on the frying pan over medium heat.  Divide the batter among them.
5.  Cook until surface bubbles hold their shape and the batter begins to dry out and lose its shine.  
6.  Flip them over and cook for another minute or so, until browned.
7.  Serve with butter, honey or jam (or use them like my mother did).

#### Substituting sourdough

I'm thinking that the above recipe could be modified to use sourdough starter in place of dry yeast and letting the batter stand overnight in a warm place.  I imagine the fresher the starter the better - perhaps use the leftover after another bread baking project.  Perhaps try a  25:25 gm (flour to water) starter, and reducing the water and flour to 75 gm and 40 gm water).

## Miscellany From the Web

### [Orecchiette with Shrimp, Pancetta, and Red Fresno Peppers](https://www.foodnetwork.com/recipes/geoffrey-zakarian/orecchiette-with-shrimp-pancetta-and-fresno-chiles-1-6557671){target="_blank"}

I found this one thanks to a facebook group devoted to Finger Lakes Wines.  It was paired with 2021 Silver Thread Estate Vineyards Riesling, which sounds excellent.

### [Blackened Grouper](https://www.gritsandpinecones.com/the-best-blackened-grouper/)

The original recipe calls for cooking indoors on a hot frying pan.  I decided to try it on the grill, and while I realized the spicing needed some adjustment, the fish cooked just fine.

**Ingredients**

> 1.5 lb. grouper filets  
> 3 tbsp melted butter  
lemon

Seasoning mix

> 2 tsp sweet paprika  
1/2 tsp cayenned pepper  
1/2 tsp black pepper  
1/2 tsp dried oregano  
1/2 tsp dried thyme  
1/2 tsp ground cumin  
1 tsp garlic powder  
1 tsp onion powder  
1 tsp brown sugar

1.  prepare your grill for high heat direct cooking (500-550^o^ F.)
1.  Combine all the ingredients of the spice mix and stir well.
2.  Blot the fish dry with paper towels.
3.  Brush melted butter on the top side of the fish and spread the spice mix over it.
4.  Flip the fish and repeat step 3.
5.  Oil a grilling basket liberally and place the fish on it.
6.  Insert a leave-in probe into the fish.
7.  Grill until the internal temperature reaches ~100^o^ F.
8.  Flip the fish and continue to grill until  it reaches an internal temperature of 125^o^ F.
9.  Squeeze lemon juice over each filet and serve.

#### Notes

The first time I made this, I followed the recipe as given, using Penzey's half sharp paprika.  The result was too hot for my tasted, so I've adjusted the recipe by calling explicitly for sweet paprika abd reducing the cayenne pepper by half.

[Penzey's](https://www.penzeys.com/shop/recipes/cajun-fish-fillets-with-mango-salsa/) suggests using just their cajun seasoning and a little oil for blackened fish - in the future I'll try combining the two recipes, replacing all of the spices with the cajun seasoning but still using the butter and brown sugar.


### Breakfast meatballs

Last weekend, we had two friends over for breakfast, and Alice suggested some kind of sausage.  I truly dislike "breakfast links", so I looked for alternatives by googling "breakfast meatballs".  I came up with two recipes and am going to try a combination of the two.  The base recipe is [here](https://www.midwestliving.com/recipe/maple-apple-glazed-breakfast-meatballs/), and I've added a few touches from [here](https://cookingprofessionally.com/recipe/breakfast-meatballs).  Since one of our guests has a genuine problem with gluten, I will use oats rather than bread crumbs as a binder.

**Ingredients**

For the meatballs:

> 3.5 oz. bacon  
> 1 egg  
1/2 cup instant oats  
1 red cooking apple, peeled and diced  
1/2 tsp dried sage  
3/4 tsp crushed fennel seeds  
1/2 tsp salt  
1/8 tsp black pepper  
1/4 tsp white pepper  
2 tsp. Worcestershire sauce  
1 lb ground pork  

For the glaze:

> 1/4 cup apple jelly  
> 1/4 cup maple syrup

1.  Fry the bacon until crisp.  Cool and dice it into fine pieces.
2.  Combine the rest of the ingredients and mix.
3.  Cover a sheet pan with foil and spray with cooking oil.
4.  Shape the meat mixture into one inch balls and place on sheet pan.
5.  Separately, combine the glaze ingredients and heat until they are smooth.
6.  Bake the meatballs at 400^o^ F. for 8-10 minutes, until they reach an internal temperature of 160 ^o^ F.
7. Drizzle the meatballs with half of the glaze and bake for two more minutes.
8.  Place the meatballs in a serving dish and drizzle with remaining glaze.

#### Notes

The times given in the recipe were too short, at least in our toaster oven.  After 10 minutes, the internal temperature was 120^o^ F; it took another 5 minutes for them to reach 160^o^.

I prepared this for our friends, both of whom are power lifters.  Suffice it to say that the meatballs disappeared instantly.  I managed to snag a couple of them, and the were quite good.

### [Grilled Korean Short Ribs](https://blog.thermoworks.com/beef/korean-shortribs-kalbi/){target="_blank"}

This needs some advance planning for marinating, but otherwise sounds like a tasty and straightforward meal.  And indeed it is - only requires about five minutes on the grill.



**Ingredients**

>1 medium onion cut into 1-inch pieces\
1 Asian pear cut into 1-inch pieces (substitute a standard pear if not available)\
5 garlic cloves\
1-inch piece fresh ginger, cut into 1/4-inch pieces\
1 C soy sauce\
1/2 C water\
1/4 C packed brown sugar\
2 Tbsp mirin\
1 Tbsp freshly ground black pepper\
4 scallions, thinly sliced\
2 Tbsp toasted sesame oil\
2 Tbsp toasted sesame seeds\
3 pounds flanken-style beef short ribs, cut about 1/4–1/2-inch thick\

1. Combine the onion, pear, garlic cloves, and fresh ginger in a food processor and process to a coarse paste.
2.  Add  thse soy sauce, water, sugar, mirin and pepper and continue to process until everything is combined.
3.  In a bowl, combine the paste with sesame seeds, sesame oil and scallions.
4.  Place the meat in a shallow pan and cover with the marinade.  Let it marinade at least one hour or overnight.
5.  Prepare your grill for cooking at 450^o^ F.
6.  Grill, turning regularly, until the internal temperatures of the ribs reaches 170^o^ F.
7.  Serve with white rice.

## Indoor "Grilling"

This year's Christmas gift from Alice was a Tupperware Micropro device, on that allows a version of grilling in your microwave.  It's a container made of some kind of material that heats when microwaved, and it has a lid that can be either placed directly on the food to be grilled or in an open position for more liquid ingredients (the "casserole" position).  To date, I have not tried the latter.

So how to use it?  The device comes with a manual that includes suggested cooking times for all sorts of things.  However, be prepared for a lot of trial and error.  So far, I've come up with one basic rule:  **Cook whatever you are doing in 3 minute intervals**.  A lot of cooking will get done, and in many cases you will want to flip your food periodically.  And go by eye - a sandwich browns nicely in 6 minutes (at least in our microwave) and chicken wings will be cooked to temperature (~175^o^ F.) in 9-12 minutes.  



### Sandwiches (Paninis)

So the basic procedure is simple:  Cut a couple of thin slices of bread, add a filling, close up into a sandwich, place in the Micropro and cook for a total of 6 minutes, flipping the sandwich after 3 minutes.  The big question, of course is what to use for a filling.  These are my results when using [Honey Wheat Sourdough Bread](#HoneyWheat):

1.  Pre-sliced supermarket "Cheddar" cheese.  Forget it.  What little flavor the cheese has is completely overwhelmed by the flavor of the bread.
2.  Pre-sliced Swiss cheese.  This is better - the bite of the cheese helps.
3.  Manchego cheese and thin-sliced Spanish Jámon.  This is the best so far - indeed it was totally delightful.  The Jámon was a gift from my son; if you don't have a local source, you can get it from [La Tienda](http://www.tienda.com).  Pricey but good.

### Chicken Wings

So far, here is what I've done.

1.  Sprinkle 8-10 wings and drumettes with barbecue rub.
2.  Cook in Micropro with microwave on high fo 3 minutes
3.  Flip chicken pieces and cook for another 3 minutes.
4.  Repeat this process until the wings appear done, and their internal temperature has reached 175^o^ F.  
5.  Coat the wings with your favorite wing sauce and serve.

#### Results

As described above, these wings are tasty but not particularly crisp.

#### Possible modifications.

1.  Stir the uncooked pieces with 1 tbsp baking powder and 1/2 tsp salt prior to sprinkling with barbecue rub.
2.  To cook the sauce into the wings, cook in the Micropro for 2-3 minutes after sauce is applied.

#### Results

The baking powder/salt mixture did crisp them up somewhat, and the salt added to the flavor.  I don't think cooking after saucing added a whole lot.  Indeed, a repeat without cooking in sauce turned out well.

#### More ideas

Epicurious has [this compilation of recipes](https://www.epicurious.com/recipes-menus/our-best-chicken-wing-recipes-gallery) that includes some tempting ideas - dry wings with curry powder, salt and pepper, coated with peach preserves, and others.  Cooking methods vary, but most could be adapted to grilling, baking, or cooking in the Micropro.



### Chicken Thighs

### Sausage and Peppers

### Quesadillas

I've always loved simple cheese quesadillas, and it struck me that the micropro might be excellent for preparing them.  It was - simply pile  up whatever filling you like on one side of a fajita-sized tortilla, fold the other side over it, and cook 3 minutes per side.  For starters, I used the following filling:

> Chicken thighs, prepared as described for [fajitas](#chfajitas)  
> Finely diced colored pepper  
> Shredded mexican cheese (or whatever you like)  
> Mexican-style hot sauce (optional)  
> Fajita-sized tortillas

1.  Prepare the chicken as described.
2.  Wipe the micropro clean and add the diced pepper.  Cook for about 6-8 minutes.
3.  Wipe the micropro again and lay a tortilla on it.
4.  Stack the chicken, pepper and cheese (however much you want) on one side of the fajita.  Season to taste with hot sauce.
5.  Fold the other side of the fajita over the ingredients.
6.  Cook for 6-8 minutes, flipping midway through.

### [Shrimp Quesadillas](https://gimmedelicious.com/shrimp-quesadillas/#recipe)

I tried this, using Penzey's Fajita Seasoning and cooking the final product in the Micropro, and had pretty good results.  I've changed a couple of steps below based on that experience.

**Ingredients**

> 1/2 pound shrimp, peeled and deveined  
> 1/2 green pepper, chopped  
> 1 medium onion, chopped  
> 2 tbsp olive olive oil, divided  
> 1 tbsp fajita seasoning  
> small bunch cilantro leaves, chopped  
> two flour tortillas, fajita size  
>  Shredded melting cheese (Mexican blend, for example)  
>  Mexican hot sauce (La Vitoria, Cholulla or similar)\

1. Combine the shrimp with the fajita seasoning, cilantro, and 1 tbsp olive oil.
2.  Sauté the pepper and onion with the other tablespoon of olive oil until soft, about 5 minutes.
3.  Add the shrimp to the pan and stir for 30 seconds to 1 minute^\*^.  Remove from heat.
4.  Place one tortilla flat in the Micropro.  Stack half the shrimp on one side, followed by cheese and hot sauce to taste.
5.  Fold the other half of the tortilla over the filling, and drape the second tortilla over the vacant half of the Micropro and the first tortilla.  Fill and fold as described for the first one.
6.  This is a place that I'm still refining.  On my first try, I cooked for 3 minutes and then attempted to flip them.  It made a mess.  Next time I'm going to let them go four minutes, and if the top is browning well, cook them for an additional two minutes and serve.

^\*^  I'm still experimenting here.  I initially tried two minutes, but that was too long.  If this proves to be too long as well, then  I'll just put them in the fajitas raw and let them cook while it browns.

## Fermentation

This will be a totally new exploration for me, arising from a [piece in Epicurious](https://www.epicurious.com/expert-advice/how-to-make-fermented-hot-sauce-article) on making fermented hot sauce.  I did a little exploration and found a [more detailed description of the process](https://www.seriouseats.com/fermented-hot-sauce-how-to) on seriouseats.com, which goes into the fermentation process in detail and includes links to the two recipes below.  I strongly recommend reviewing this before you begin, but the key points are that for the process to proceed, we have to establish an anaerobic saline environment, allowing lactic acid-producing bacteria to flourish.
I'm going to attempt to do so in one quart mason jars, with vapor locks and weights [obtained from Amazon](https://www.amazon.com/gp/product/B089N21NTB/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1).  The recipes that follow use the two preparations  most commonly used for fermentation - a mash and a salt brine.

### [A Generic Fermented Hot Sauce Recipe](https://nourishedkitchen.com/fermented-hot-chili-sauce-recipe/)

The idea here would be to experiment with different red or orange peppers and see what tastes good.  Don't worry about the occasional failure.

### [Habernero and Berry Hot Sauce](https://www.seriouseats.com/double-berry-habanero-hot-sauce)

First, a mash preparation - looks pretty straight forward.

**Ingredients**

> 225 grams each (8 oz) of blackberries and blueberries  
> 150 g. habernero peppers (about 25), stemmed  
> 30 gm. salt  
> 1/4 cup white vinegar  
> 10 gm sugar  

1.  Using a food processor, pulse the berries, peppers and salt into a coarse puree, about 12 pulses.
2.  Transfer to a 1 quart Mason canning jar.   Cover the surface with plastic wrap and place a weight on top of it.
3.  Seal the jar with an air lock.
4.  Store the jar in a cool dark place for at least seven days, checking daily for gas formation.  The mix should taste sour, having a pH of 4.2 or less.
5.  Transfer the mash to a blender, adding the sugar and vinegar.  
6.  Blend on high speed until smooth.  Check the pH - it should be about 3.4.  Add more vinegar if needed.
6.  Strain the mixture through a fine sieve and discard the pulp (although you might want to save it as a flavoring for other foods).
7.  Store refrigerated in a glass bottle or plastic squeeze bottle.  The original recipe says it will keep for up to a month; we'll see if it goes longer.

### [Chipotle Fermented Hot Sauce with Garlic and Cumin](https://www.seriouseats.com/chipotle-garlic-and-cumin-fermented-hot-sauce)

This recipe involves use of the salt brine method, and also uses dried rather than fresh peppers.  In addition to adding flavor, the fresh garlic is the source of the naturally occurring lactobacilli necessary for fermentation.

**Ingredients**

> 3 cups bottled water^\*^  
> 30 gm salt  
> 55 gm dried chipotle morita peppers (about 20 peppers)  
> 6 cloves garlic, sliced  
> 5 gm cumin seeds, lightly toasted  
> 3/4 cup white vinegar  
> 15 gm sugar  
> Kosher salt

1.  Mix water and salt until the salt is dissolved.
2.  Add peppers, garlic and cumin to a 1 quart Mason jar.
3.  Add brine, cover with plastic, add a weight and seal with air lock.
4.  Store in a dark cool place for at least 10 days, checking frequently for gas formation.
5.  After 10 days, taste daily, until it tastes sour like dill pickles - could take up to 28 days.
6.  Strain out brine with a fine sieve, retaining the saline for now.
7.  Transfer solids to a blender and add 1 cup of the brine along with the sugar and vinegar.
8.  Blend at high speed until smooth and emulsified.  Season with salt.
9.  Measure the pH of the sauce.  It should be at or below 3.4; add more vinegar if necessary.
10.  Strain the mixture again and bottle the sauce.
11.  Store refrigerated for up to 3 months.

^\*^ This is one case where use of tap water is not recommended, as it is likely contain traces of chlorine that will inhibit bacterial growth.  Bottled spring  water is the best bet.

### [Hot Sauce with Fresno Chiles, Garlic, and Tamari](https://www.seriouseats.com/charred-fresno-tamari-and-roasted-garlic-fermented-hot-sauce)

This one is interesting - uses a mixture of broiled and fresh peppers.

**Ingredients**


For fermentation

> 700 gm  stemmed Fresno peppers  
60 ml distilled water  
3 tbsp tamari soy sauce  
10 gm kosher salt  

For finishing

> 120 ml white vinegar  
10 gm. sugar  
2 tsp kosher salt  
120 ml roasted garlic oil

1.  Broil 300 gm of the peppers until charred, about 5 minutes per side.  Allow them to cool.
2.  Combine the charred peppers, the remaining (400 gm) fresh peppers, water, salt and tamari in a food processor.  Pulse 16-20 times into a coarse mash.
3.  Transfer to a 1 quart canning jar and set up with weight and airlock for fermentation. there should be about an inch of head space
4.  Let fermentation proceed for 7-21 days, until mash has climbed up the side of the jar and the pH has dropped below 4.0
5.  Scrape the mash into a blender.  Add vinegar, sugar and salt, and blend until smooth (~1 minute).
6.  With blender running stream in garlic oil and continue to blend until it is emulsified.  
7.  Check the pH - if it is over 3.4, add more vinegar.
8.  Strain through a fine strainer, transfer to a clean bottle, and refrigerate.

