# Links to Follow

The abundance of cooking information on the web can be both a blessing and a curse - it provides a seemingly infinite source of new recipes and ideas, but it also can  be so overwhelming that items of interest are easily lost. This section will be my repository for recipes I find that I may want to explore in the future, particularly those I have liked on major sites.  They are provided here in no particular order and with minimal comments - as I try them out, I will flesh things out and move them to appropriate sections of the book.

## [New York Times Cooking](https://cooking.nytimes.com/){target="_blank"}

### [Chicken Teryaki](https://cooking.nytimes.com/recipes/1012984-chicken-teriyaki){target="_blank"}

This one was recommended by Jamelle Bouie in his weekly newsletter.  He recommends using orange juice in place of pineapple and cooking on skewers.  Sounds good.

### [Stuffed Shells](https://cooking.nytimes.com/recipes/1020833-stuffed-shells){target="_blank"}

Actually, I've cooked this one many times.

### [Marinara Sauce](https://nourishplate.com/instant-pot-marinara/){target="_blank"}

Good basic recipe; probably could  use some crushed red pepper and maybe fennel.

### [Naan](https://cooking.nytimes.com/recipes/1017747-meera-sodhas-naan)

### [Pita](https://cooking.nytimes.com/recipes/1016071-homemade-pita-bread)

This worked very well the first time I tried it.  I then ate them stuffed with a variety of leftovers in the refrigerator.  

### [Sazon Chicken](https://cooking.nytimes.com/recipes/1023058-sazon-chicken-breasts){target="_blank"}

This calls for breast meat; I'm going to try it with thighs. 

### [Linguine with Lemon Sauce](https://cooking.nytimes.com/recipes/1589-linguine-with-lemon-sauce){target="_blank"}
 
### Shrimp Masala

### Chicken with Harissa, citrus and dates

### [Chicken Tikka](https://cooking.nytimes.com/recipes/1023895-chicken-tikka){target="_blank"}

This is one of my favorite dishes from my favorite Indian restaurant.   A reader on the NYT site suggested a sauce for use when serving over rice.  I've included that here as well.

**Ingredients**

> six boneless skinless chicken thighs, cut into 1 inch pieces  
1/4 cup malt vinegar or lemon juice  
1 +1/2 tsp kosher salt  
1 cup plain yogurt  
3 tbsp malt vinegar  
2-3 tsp Kashmiri chilli powder ("deggi murch")  
1 tbsp garam masala  
1 tsp turmeric  
4 + 4 tsp. ginger garlic paste  
1/4 cup melted butter  

1.  In a bowl, combine the chicken with the lemon juice, 1 tsp salt and 4 tsp. ginger garlic paste.  Let it rest 10 minutes.
2.  Mix together the yogurt, malt vinegar, chilli powder, garam masala, turmeric, 1/2 tsp salt, and 4 tsp ginger garlic paste in another bowl.
3.  Blot the chicken dry and add it to the yogurt mixture.  Refrigerate for 3-4 hours.
4.  Prepare your grill and heat it to 450^o^ F.
5.  Put the chicken on skewers and grill, turning occasionally, until the internal temperature of the chicken reaches ~160^o^ F.
6.  Serve with naan or over rice.

NOTE:  A while back, I tried using the Egg as a Tandoor oven as described [here](https://halalbbqpitmasters.com/blogs/techniques/can-a-kamado-grill-function-as-a-tandoor-oven){target="_blank"}.  It involves using long skewers that are positioned through the upper vent of a very hot Egg.  Those results were so-so, but it might be worth trying again.  As best I can tell, the cook time would be ~10 minutes.

**Suggested Sauce**

> Leftover second marinade  
> 1 14 oz can fire-roasted tomatoes  
> 1-2 tsp. curry powder  
> 1 tsp. garam masala

1.  Combine ingredients, bring to a simmer, and serve.

## [Epicurious]

## [Thermoworks](https://blog.thermoworks.com){target="_blank"}

### [Grilled Lobster](https://blog.thermoworks.com/bbq-grilling/grill-lobster){target="_blank"}

## Other

### [IP Chocolate Cake](https://recipes.instantpot.com/recipe/fudgy-chocolate-cake/){target="_blank"}

### [IP Turtle Cheesecake](https://www.365daysofcrockpot.com/pressure-cooker-turtle-cheesecake/){target="_blank"}

### [Instant Pot® Ghee](https://www.paintthekitchenred.com/homemade-instant-pot-ghee/){target="_blank"}

