---
title: "Cooking After Retirement"
author: "Bruce Cochrane"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: bjcochrane/CookBook
---

# Front Matter {.unnumbered}

## Dedication {.unnumbered}

My adventures in the kitchen date back to my childhood, and I am actually thankful that neither my mother nor my father (Vince and Jean Cochrane) liked to cook, so they eagerly encouraged my childhood desire to explore. As an adult, my family - both my first wife, the late Barbara Leyden, and my second, Alice Kahn, provided encouragement and constructive criticism where necessary. Finally, my two sons, Steven and John Cochrane, are continuing the cooking tradition - Steven as a vegetarian and John as a budding pitmaster. This book is lovingly dedicated to all of them.

<center>

*Updated `r format(Sys.Date(),format="%B %d %Y")`*

</center>

## A Note on Production {.unnumbered}

This book was prepared using the [Rstudio](http://www.rstudio.com) [bookdown](http://www.bookdown.org) package. This means that the writing is done using [markdown](https://www.markdownguide.org/) syntax, which is then rendered into html, pdf, and epub versions. My knowledge of markdown is not negligible (I used it a lot in the later part of my career), but neither is it extensive. Furthermore, I am much more interested in writing about food than in dealing with the intracacies of formatting and publishing, so I've kept things pretty basic. I hope this works for you.

Among other features, this combination of tools makes it relatively easy to insert images, although its ability to position them and add fancy features is (at least in my hands) rather limited. Thus, most of the figures are at the end of subsections, and panels contain no more than two images. Also, again for the sake of convenience, I took most of the photos with my iphone. I tried to compose the image somewhat, but some of them are a bit on the crude side.
